
# default port
server:
  port: 8080
spring:
  application:
    name: @project.name@
  profiles:
    active: dev
# eureka config
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 30
    service-url.default-zone: http://@rno.registry.host@:8761/eureka
#断路器超时，需与负载均衡超时配合使用，否则将出现多次重复动作
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3600000

ribbon:
  #负载均衡读取超时，应不小于断路器超时
  ReadTimeout: 3600000
  #负载均衡连接超时，一般与读取超时相等
  ConnectTimeout: 3600000

# log
logging:
  level:
    root: warn
    com.hgicreate.rno: debug
# RNO setting

# service config
rno:
  lte.service:
    common: rno-lte-common-service
    azimuth-evaluation: rno-lte-azimuth-evaluation-service
    pci-afp: rno-lte-pci-afp-service

---

spring:
  profiles: dev
  # datasource config
  datasource:
     url: jdbc:postgresql://192.168.9.66:5432/rno_pci
     username: rno_pci
     password: RnoPci@2017